version: "3"

services:
    web:
        build: .
        ports:
            - "8000:8000"
        volumes:
            - .:/celery
        command: bash -c "django-admin startproject config && mv config app"
