version: "3"

services:
    web:
        build: .
        ports:
            - "8000:8000"
        volumes:
            - .:/celery
        working_dir: /celery/app
        command: python manage.py runserver 0.0.0.0:8000
